services:
  postgres:
    image: postgres:18
    container_name: poe-postgres
    restart: unless-stopped
    hostname: pgdb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:8
    container_name: poe-redis
    restart: unless-stopped
    hostname: bullmq
    environment:
      REDIS_PASSWORD: ${BULLMQ_PASSWORD}
    command: ["redis-server", "--requirepass", "${BULLMQ_PASSWORD}"]
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  poe-call-management:
    container_name: poe-call-management
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "${CALL_MANAGEMENT_PORT:-3000}:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      CALL_MANAGEMENT_PORT: ${CALL_MANAGEMENT_PORT:-3000}
      CALL_MANAGEMENT_HOSTNAME: ${CALL_MANAGEMENT_HOSTNAME:-127.0.0.1}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_POOL_SIZE: ${DATABASE_POOL_SIZE}
      JWT_SECRET: ${JWT_SECRET}
      BULLMQ_HOST: ${BULLMQ_HOST}
      BULLMQ_PORT: ${BULLMQ_PORT}
      BULLMQ_PASSWORD: ${BULLMQ_PASSWORD}
      BULLMQ_GLOBAL_CONCURRENCY: ${BULLMQ_GLOBAL_CONCURRENCY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
